services:
  postgres:
    container_name: fast-feet-api
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: postgres_fast_feet
      POSTGRESQL_PASSWORD: docker_fast_feet
      POSTGRESQL_DATABASE: fast_feet_api
    volumes:
      - fast_feet_pg_data:/bitnami/postgresql

volumes:
  fast_feet_pg_data:
